### ISSUE TITLE
Problem by using Neo4j 3.3.1

### ISSUE THREAD

**Issue by DexterZeng** [mirkonasato/graphipedia#11]
Hi:

Thanks for sharing the code :)

Following what is stated in README, I have changed the version of neo4j to 3.3.1 in the pom.xml file. However, when I execute the command mvn install, there was an error indicating that in ImportGraph.java [37,44], java.lang.String cannot be converted to java.io.File. Now I am reading the code and trying to fix this error, but considering that  it has been 2 years since you last updated the code, I  am worried that there might be other potential problems. Could you please check the code again? It would be of much help!

Many thanks for your time :)

**Comment by baituhuangyu** [comment]
public ImportGraph(String dataDir) throws Exception {
        File dataFile = new File(dataDir);
        inserter = BatchInserters.inserter(dataFile);
        inserter.createDeferredSchemaIndex(WikiLabel.Page).on("title").create();
        inMemoryIndex = new HashMap<String, Long>();
    }

**Comment by mirkonasato** [comment]
Should be fixed by 859cd5d
