### ISSUE TITLE
Diffifulties to import the graphdb into NEO4j

### ISSUE THREAD

**Issue by cafeine05** [mirkonasato/graphipedia#3]
Hi,

I succeed in creating the graphdb directory but trying to import into Neo4j 2.1.7 I got this message : 

"Starting Neo4j Server failed: Error starting org.neo4j.kernel.EmbeddedGraphDatabase, C:\Users\Joubert\Documents\Neo4j\graphdb"

Can you help me ? Maybe it is not the good version of Neo4j ?

Sincerely yours.

**Comment by mirkonasato** [comment]
Please provide more details, like what command you executed, full error stack trace etc.

**Comment by cafeine05** [comment]
Thank you for your rapid answer, but i found the solution yet by
downloading the 1.4.2 version of Neo4j :) But now i have an other problem :
when I wrote the cypher request :

MATCH (p0:Page {title:'Neo4j'}) -[Link]- (p:Page) RETURN p0, p

it gave "Missing START Clause". Can you give me the whole process to get a
graph of all link from one page in the cypher console ?

Le Wed Feb 04 2015 at 20:47:31, Mirko Nasato <notifications@github.com> a
écrit :

**Comment by thomir** [comment]
Hi,

I also have this issue - is this supposed to work with neo4j v2.1.7? I'm new to neo4j, so I'm probably doing something stupid. Below is a selection of commands I've tried, and their error messages:

```
$ neo4j-shell -path graphdb/
ERROR (-v for expanded information):
	Error starting org.neo4j.kernel.EmbeddedGraphDatabase, /home/thomi/code/graphipedia/graphdb

$ neo4j-shell -path graphdb/neostore.nodestore.db
ERROR (-v for expanded information):
	java.io.FileNotFoundException: graphdb/neostore.nodestore.db/messages.log (Not a directory)

$ neo4j-shell -path graphdb/neostore.schemastore.db
ERROR (-v for expanded information):
	java.io.FileNotFoundException: graphdb/neostore.schemastore.db/messages.log (Not a directory)

```

Any hints as to how to get this going?

Thanks!

**Comment by mirkonasato** [comment]
The project was last updated for neo4j v2.0.0, haven't tried more recent versions.

You probably need to change the neo4j.version property in the pom.xml and rebuild, I can imagine that if you create a database with v2.0 and then try to open it with v2.1 it may not work.

**Comment by thomir** [comment]
Hi,

I managed to fix this with a combination of building with '2.1.0' in pom.xml, and starting neo4j-shell with the allow_store_upgrade property in neo4j.properties file set to 'true'.


Thanks for your help.

**Comment by mirkonasato** [comment]
I've now updated the dependencies to neo4j v2.1.7.
