### ISSUE TITLE
Update to 2.2 by using docker

### ISSUE THREAD

**Issue by pdonorio** [mirkonasato/graphipedia#5]
Dear Mirko,
thanks for your great work.

I am trying to import your graphdb inside the latest release of neo4j:
http://neo4j.com/blog/neo4j-2-2-0-scalability-performance

The first time i was asked by neo4j to update the database with a special property, 
and after upgrading the server crashed with no log and no clear issues.

Since i am using Docker, a very easy and convenient system for isolations of applications inside container, may i ask you to rebuild the db using the updated neo4j version?

The docker image is available here:
https://registry.hub.docker.com/u/kbastani/docker-neo4j/

It also contains clear instructions on how to use if you have docker installed.
If you have problems on installing docker or using the image i may help you.
I may also build a dev environment for this.

Thanks,
Paolo

**Comment by mirkonasato** [comment]
The neo4j version used by graphipedia is specified as a property in the pom.xml - just change it to 2.2.0 and rebuild.

I'll add some instructions to the readme file since you're not the first person who complains about incompatible versions.

**Comment by mirkonasato** [comment]
Updated neo4j.version to 2.2.0 and added instructions to the README.

**Comment by pdonorio** [comment]
Thanks a lot!
