### ISSUE TITLE
IlligalStateException

### ISSUE THREAD

**Issue by pedropgusmao** [mirkonasato/graphipedia#7]
`Exception in thread "main" java.lang.IllegalStateException: Misaligned file size 68 for DynamicArrayStore[fileName:neostore.nodestore.db.labels, blockSize:60], expected version length 25`

Hi, I am getting this error, am I doing something wrong?

Thanks,
Pedro

**Comment by mirkonasato** [comment]
I don't know. What did you do to get that error?

**Comment by pedropgusmao** [comment]
Thanks for your rapid response,
Well, I ran the following command:
`java -Xmx3G -classpath graphipedia-dataimport/target/graphipedia-dataimport.jar org.graphipedia.dataimport.neo4j.ImportGraph  /media/datasets/enwiki-links.xml graphdb `

from the extracted graphipedia folder after extracting the wiki links into `/media/datasets/enwiki-links.xml`

my java version is:  
`java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)`

and I have set `<neo4j.version>2.2.3</neo4j.version>` in the pox.xml file.

Thanks for your help

**Comment by viswanath7** [comment]
I also receive the same exception when I try and a bulk insert 
Caused by: java.lang.IllegalStateException: Misaligned file size 68 for DynamicArrayStore[fileName:neostore.nodestore.db.labels, blockSize:60], expected version length 25

**Comment by mirazour** [comment]
Is there any update on this issue? I'm dealing with the same error, and I have followed the project instructions for setting up the project - not sure what's wrong at this point.

**Comment by mirkonasato** [comment]
I can't reproduce the issue I'm afraid.
