### ISSUE TITLE
Database files require upgrading

### ISSUE THREAD

**Issue by znorris** [mirkonasato/graphipedia#8]
I get the following message when attempting to use the database created by graphipedia:
```
ERROR Neo4j cannot be started, because the database files require upgrading and upgrades are disabled in configuration. Please set 'allow_store_upgrade' to 'true' in your configuration file and try again.
```

Setting `allow_store_upgrade=true` results neo4j not responding to http requests. I don't see any logs generated either. I'm using the official docker image like this:
```
docker run \
    --name neo4j-wiki \
    --rm \
    --publish=7474:7474 \
    --volume=$HOME/neo4j/data:/data \
    --volume=$HOME/neo4j/conf:/conf \
    --env=NEO4J_CACHE_MEMORY=2G \
    --env=NEO4J_HEAP_MEMORY=4G \
    neo4j:2.3.2
```
In the `neo4j-server.properties` I've set `allow_store_upgrade=true` and `org.neo4j.server.database.location=data/wikipedia.db`.

**Comment by mirkonasato** [comment]
Like the [readme](https://github.com/mirkonasato/graphipedia#building) says

> Check the neo4j.version property in the top-level pom.xml file and make sure it matches the Neo4j version you intend to use to open the database. Then build [...]

**Comment by znorris** [comment]
Thanks, sorry for not reading the manual. When using the generated DB neo4j still doesn't accept incoming HTTP connections. However it no longer requests to upgrade. I'll see if I can't get some more debug output. Thanks again.
